import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import type React from "react";

const nunito = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased bg-midnight-950 text-natural-100`}
      >
        {children}
      </body>
    </html>
  );
}
